version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /root/inpaint_mongo_data:/data/db
  app:
    build: .
    depends_on:
      - mongo
    environment:
      LANG: C.UTF-8
      TZ: Europe/Moscow
    ports:
      - 5000:8003
