version: '3'
services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - /root/inpaint_mongo_data:/data/db

  admin_mongo:
    image: adicom/admin-mongo
    restart: always
    depends_on:
      - mongo
    ports:
      - 8004:1234

  app:
    build: .
    volumes:
      - ./app/prometheus/client_data:/etc/prometheus/client_data
    depends_on:
      - mongo
    environment:
      LANG: C.UTF-8
      TZ: Europe/Moscow
      prometheus_multiproc_dir: /etc/prometheus/client_data
    ports:
      - 8003:5000

  prometheus:
    image: prom/prometheus:v2.3.1
    volumes:
      - ./app/prometheus/data:/etc/prometheus/data
      - ./app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./app/prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/data'
    depends_on:
      - app
