version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /root/inpaint_mongo_data:/data/db
  admin_mongo:
    image: adicom/admin-mongo
    restart: always
    depends_on:
      - mongo
    ports:
      - 8004:1234
  app:
    build: .
    depends_on:
      - mongo
    environment:
      LANG: C.UTF-8
      TZ: Europe/Moscow
    ports:
      - 8003:5000
