global:
  scrape_interval:     10s
  evaluation_interval: 10s

  external_labels:
      monitor: 'inpaint'

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']

rule_files:
  - /etc/prometheus/rules.yml
